name: expense_tracker
description: A Flutter app for tracking expenses via SMS and Notion integration
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  telephony: ^0.2.0 # Replace sms_advanced with telephony
  http: ^1.2.2 # For making HTTP requests to Notion and Flask
  provider: ^6.1.2 # For state management
  permission_handler: ^11.3.1 # For requesting SMS permissions
  cupertino_icons: ^1.0.8 # Default icons for UI

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true